language: java
jdk:
  - openjdk7

install: true
script: ./travis.sh

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  file:
    - "./target/svg-maven-plugin-$TRAVIS_TAG.jar"
